### ISSUE TITLE
FileNotFoundError:No such file or directory: './Automatic-Rigging/README.rst'

### ISSUE THREAD

**Issue by wuyiqii** [haoz19/Automatic-Rigging#1]
Thank you for your wonderful work.
But when I try to do "python setup.py install"，there does not appear to be a 'README.rst' file in the 'automation-rigging/' directory.
Can you provide this file or how should I modify the setup.py file?

**Comment by wuyiqii** [comment]
I tried to convert the existing README.md in the folder to a README.rst file, and then I ran into this problem:‘subprocess.CalledProcessError: Command '['cmake', './Automatic-Rigging', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=./Automatic-Rigging/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=./Anaconda3/envs/magic/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.’

**Comment by haoz19** [comment]
Hi, thanks for pointing out the error, please try the updated command! let me know if you have more questions.

**Comment by Eamon-0v0** [comment]
> I tried to convert the existing README.md in the folder to a README.rst file, and then I ran into this problem:‘subprocess.CalledProcessError: Command '['cmake', './Automatic-Rigging', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=./Automatic-Rigging/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=./Anaconda3/envs/magic/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.’

I'm still experiencing this problem, have you solved it yet?

**Comment by Net-Maker** [comment]
For the question about README, please refer to the original pynocchio repo to get the README.rst. [repo](https://github.com/alexanderlarin/pynocchio).
For the question about Cmake Error, I found that it's due to the cmake cannot find pybind11, refer to this [issue](https://github.com/pybind/pybind11/issues/2229).
You can solve this by trying `sudo apt install python3-pybind11` or `pip install pybind11`, the first command works for me.
